app:
  url: http://locahost:8080

compiler:
  working-dir: /data/java-explorer
  build-dir: build
  compilers:
    - name: openjdk8
      cmd: javac -d build {OPTS} {SRC_FILES}
      example: examples/java/Main.java
    - name: openjdk11
      cmd: javac -d build {OPTS} {SRC_FILES}
      example: examples/java/Main.java
    - name: kotlin1.7.20
      cmd: kotlinc -d build {OPTS} {SRC_FILES}
      example: examples/kotlin/Main.kt

