app:
  url: http://locahost:8080

compiler:
  working-dir: /opt/app
  build-dir: build
  compilers:
    - name: openjdk8
      cmd: javac -d build {OPTS} {SRC_FILES}
    - name: openjdk11
      cmd: javac -d build {OPTS} {SRC_FILES}

